# Generated by Django 4.2.3 on 2023-07-14 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo')),
            ],
            options={
                'verbose_name': 'logo',
                'verbose_name_plural': 'logolar',
            },
        ),
        migrations.CreateModel(
            name='PersonInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='person_photo')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiýasy')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ady')),
                ('patronic_name', models.CharField(max_length=100, verbose_name='Atasynyň ady')),
                ('second_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gyz familiýasy')),
                ('begining_of_work', models.DateField(verbose_name='Işe giren senesi:')),
                ('degree_of_work', models.CharField(blank=True, max_length=50, null=True, verbose_name='Buýrugyň belgisi')),
                ('order_of_work', models.CharField(blank=True, max_length=50, null=True, verbose_name='Permanyň belgisi')),
                ('birth_certificate_id', models.CharField(max_length=50, verbose_name='Dogluş hakynda şahadatnamasynyň belgisi')),
                ('passport_id', models.CharField(max_length=50, verbose_name='Pasport belgisi')),
                ('passport_address', models.CharField(max_length=250, verbose_name='Pasport kim tarapyndan berildi')),
                ('passport_date', models.DateField(verbose_name='Pasport berlen senesi')),
                ('date_of_birthday', models.DateField(verbose_name='Doglan senesi')),
                ('birthday_place', models.CharField(max_length=250, verbose_name='Doglan ýeri')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Raýatlylygy')),
                ('nationality', models.CharField(max_length=100, verbose_name='Milleti')),
                ('address', models.CharField(max_length=250, verbose_name='Ýazgyda duran salgysy')),
                ('exactly_address', models.CharField(max_length=250, verbose_name='Hakyky salgysy salgysy')),
                ('foreign_languages', models.CharField(blank=True, max_length=100, null=True, verbose_name='Haýsy daşary ýurt dillerini bilýär')),
                ('is_election', models.CharField(max_length=100, verbose_name='Saýlawly edaralara gatnaşmagy')),
                ('height', models.SmallIntegerField(verbose_name='Boýy')),
                ('weight', models.SmallIntegerField(verbose_name='Agramy')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefon belgisi')),
                ('phone_number_1', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefon belgisi 2')),
                ('marital_status', models.CharField(max_length=100, verbose_name='Maşgala ýagdaýy')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_author', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='person_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Işgär',
                'verbose_name_plural': 'Işgärler',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_experience', models.SmallIntegerField(verbose_name='Umumy iş döwri')),
                ('experience_in_court', models.SmallIntegerField(verbose_name='Kazyýetde iş döwri')),
                ('experience_in_army', models.SmallIntegerField(verbose_name='Harby gulluk döwri')),
                ('experience_in_education', models.SmallIntegerField(verbose_name='Ýokary okuw döwri')),
                ('experience_in_last_position', models.SmallIntegerField(verbose_name='Soňky wezipedäki iş döwri')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_WorkExperience', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Iş stažy barada maglumat',
                'verbose_name_plural': 'Iş stažy barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='WasHeAbroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_country', models.CharField(max_length=100, verbose_name='Ýurduň ady')),
                ('date', models.DateField(verbose_name='Senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_WasHeAbroad', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Daşary ýurtda bolandygy barada maglumat',
                'verbose_name_plural': 'Daşary ýurtda bolandygy barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Buýrugyň belgisi')),
                ('order_date', models.DateField(verbose_name='Buýrugyň senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_Vacation', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Esasy zähmet rugsady barada maglumat',
                'verbose_name_plural': 'Esasy zähmet rugsady barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='UnpaidLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Buýrugyň belgisi')),
                ('order_date', models.DateField(verbose_name='Buýrugyň senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_UnpaidLeave', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Tölegsiz rugsady barada maglumat',
                'verbose_name_plural': 'Tölegsiz rugsady barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='StateAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_award', models.CharField(max_length=250, verbose_name='Döwlet sylagynyň ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Permanyň belgisi')),
                ('order_date', models.DateField(verbose_name='Permanyň senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_StateAwards', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Döwlet sylaglary barada maglumat',
                'verbose_name_plural': 'Döwlet sylaglary barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Buýrugyň belgisi')),
                ('order_date', models.DateField(verbose_name='Buýrugyň senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_Rewards', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Döşe dakylýan nyşany barada maglumat',
                'verbose_name_plural': 'Döşe dakylýan nyşany barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='RelativesLivingAbroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ady, Familiýasy')),
                ('country_name', models.CharField(max_length=100, verbose_name='Ýurduň ady')),
                ('start_date', models.DateField(verbose_name='Giden senesi')),
                ('end_date', models.DateField(verbose_name='Gelen senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_RelativesLivingAbroad', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Ýakyn garyndalaşlary daşary ýurtda ýaşaýanlar barada maglumat',
                'verbose_name_plural': 'Ýakyn garyndalaşlary daşary ýurtda ýaşaýanlar barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Buýrugyň belgisi')),
                ('order_date', models.DateField(verbose_name='Buýrugyň senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_Punishment', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Düzgün nyzam jogapkärçiligine çekilmegi barada maglumat',
                'verbose_name_plural': 'Düzgün nyzam jogapkärçiligine çekilmegi barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='PersonEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_university', models.CharField(max_length=100, verbose_name='Gutaran ýeri')),
                ('name_of_university', models.CharField(max_length=250, verbose_name='Tamamlan okuw jaýy')),
                ('date_of_finishing_university', models.DateField(verbose_name='Okuwy tamamlan ýyly')),
                ('diploma_id', models.CharField(max_length=50, verbose_name='Diplom belgisi')),
                ('name_of_academy', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ýokary okuw jaýyndan soňky okan ýeri')),
                ('date_of_finishing_academy', models.DateField(blank=True, null=True, verbose_name='Ýokary okuw jaýyndan soňky okuwy tamamlan ýyly')),
                ('academy_diploma_id', models.CharField(blank=True, max_length=50, verbose_name='Akademiýanyň diplom belgisi')),
                ('remote', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gündizki')),
                ('full_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gaýbana')),
                ('confirmation_of_education', models.CharField(blank=True, max_length=250, null=True, verbose_name='Daşary ýurt diplomyny ykrar edilendigi barada maglumat')),
                ('date_of_confirmation', models.DateField(blank=True, null=True, verbose_name='Daşary ýurt diplomyny ykrar edilen senesi')),
                ('education_degree', models.CharField(max_length=50, verbose_name='Bilimi')),
                ('major', models.CharField(max_length=100, verbose_name='Hünäri')),
                ('scientific_degree', models.CharField(max_length=100, verbose_name='Alymlyk derejesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Bilimi barada maglumat',
                'verbose_name_plural': 'Bilimi barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='ParticipateInElections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=250, verbose_name='Bellik')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_ParticipateInElections', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Saýlawly edaralara gatnaşmagy barada maglumat',
                'verbose_name_plural': 'Saýlawly edaralara gatnaşmagy barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='HealthVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Buýrugyň belgisi')),
                ('order_date', models.DateField(verbose_name='Buýrugyň senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_HealthVacation', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Zähmete ukypsyzlgy boýunça rugsady barada maglumat',
                'verbose_name_plural': 'Zähmete ukypsyzlgy boýunça rugsady barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='CriminalLiability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ady')),
                ('date', models.DateField(verbose_name='Senesi')),
                ('court_info', models.CharField(max_length=200, verbose_name='Ady')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_CriminalLiability', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Ýakyn garyndalaşlary jenaýat jogapkärçiligi barada maglumat',
                'verbose_name_plural': 'Ýakyn garyndalaşlary jenaýat jogapkärçiligi barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Awtoulagyň ady')),
                ('date_manufacture', models.DateField(verbose_name='Öndürilen senesi')),
                ('is_own', models.CharField(max_length=100, verbose_name='Awtoulag kimiň adyna resmilleşdirilen')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_CarInfo', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Awtoulagy barada maglumat',
                'verbose_name_plural': 'Awtoulagy barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_country', models.CharField(max_length=100, verbose_name='Ýurduň ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Buýrugyň belgisi')),
                ('order_date', models.DateField(verbose_name='Buýrugyň senesi')),
                ('start_date', models.DateField(verbose_name='Giden senesi')),
                ('end_date', models.DateField(verbose_name='Gelen senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_BusinessTrip', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Iş sapary barada maglumat',
                'verbose_name_plural': 'Iş sapary barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='AppreciationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Buýrugyň belgisi')),
                ('order_date', models.DateField(verbose_name='Buýrugyň senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_AppreciationLetter', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Hormat hatlary barada maglumat',
                'verbose_name_plural': 'Hormat hatlary barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='AdditionalVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Buýrugyň belgisi')),
                ('order_date', models.DateField(verbose_name='Buýrugyň senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_AdditionalVacation', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Goşmaça rugsady barada maglumat',
                'verbose_name_plural': 'Goşmaça rugsady barada maglumatlar',
            },
        ),
    ]
