# Generated by Django 4.2.3 on 2023-07-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo')),
            ],
            options={
                'verbose_name': 'logo',
                'verbose_name_plural': 'logolar',
            },
        ),
        migrations.CreateModel(
            name='PersonInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='person_photo')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiýasy')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ady')),
                ('patronic_name', models.CharField(max_length=100, verbose_name='Atasynyň ady')),
                ('second_name', models.CharField(max_length=100, verbose_name='Gyz familiýasy')),
                ('begining_of_work', models.DateField(verbose_name='Işe giren senesi:')),
                ('degree_of_work', models.CharField(blank=True, max_length=50, verbose_name='Buýrugyň belgisi')),
                ('order_of_work', models.CharField(blank=True, max_length=50, verbose_name='Perkanyň belgisi')),
                ('birth_certificate_id', models.CharField(max_length=50, verbose_name='Dogluş hakynda şahadatnamasynyň belgisi')),
                ('passport_id', models.CharField(max_length=50, verbose_name='Pasport belgisi')),
                ('passport_address', models.CharField(max_length=250, verbose_name='Pasport belgisi')),
                ('passport_date', models.DateField(verbose_name='Pasport berlen senesi')),
                ('date_of_birthday', models.DateField(verbose_name='Doglan senesi')),
                ('birthday_place', models.CharField(max_length=250, verbose_name='Doglan ýeri')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Raýatlylygy')),
                ('nationality', models.CharField(max_length=100, verbose_name='Milleti')),
                ('address', models.CharField(max_length=250, verbose_name='Ýazgyda duran salgysy')),
                ('exactly_address', models.CharField(max_length=250, verbose_name='Hakyky salgysy salgysy')),
                ('foreign_languages', models.CharField(max_length=100, verbose_name='Haýsy daşary ýurt dillerini bilýär')),
                ('is_election', models.CharField(max_length=100, verbose_name='Saýlawly edaralara gatnaşmagy')),
                ('height', models.SmallIntegerField(verbose_name='Boýy')),
                ('weight', models.SmallIntegerField(verbose_name='Agramy')),
                ('phone_number', models.CharField(blank=True, max_length=12, verbose_name='Telefon belgisi')),
                ('phone_number_1', models.CharField(blank=True, max_length=12, verbose_name='Telefon belgisi 2')),
                ('marital_status', models.CharField(max_length=100, verbose_name='Maşgala ýagdaýy')),
            ],
            options={
                'verbose_name': 'Işgär',
                'verbose_name_plural': 'Işgärler',
            },
        ),
    ]
