# Generated by Django 4.2.3 on 2023-07-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_university', models.CharField(max_length=100, verbose_name='Gutaran ýeri')),
                ('name_of_university', models.CharField(max_length=250, verbose_name='Tamamlan okuw jaýy')),
                ('date_of_finishing_university', models.DateField(verbose_name='Okuwy tamamlan ýyly')),
                ('diploma_id', models.CharField(max_length=50, verbose_name='Diplom belgisi')),
                ('name_of_academy', models.CharField(blank=True, max_length=200, verbose_name='Ýokary okuw jaýyndan soňky okan ýeri')),
                ('date_of_finishing_academy', models.DateField(blank=True, verbose_name='Ýokary okuw jaýyndan soňky okuwy tamamlan ýyly')),
                ('academy_diploma_id', models.CharField(blank=True, max_length=50, verbose_name='Akademivanyň diplom belgisi')),
                ('remote', models.CharField(blank=True, max_length=10, verbose_name='Gündizki')),
                ('full_time', models.CharField(blank=True, max_length=10, verbose_name='Gaýbana')),
                ('confirmation_of_education', models.CharField(blank=True, max_length=250, verbose_name='Daşary ýurt diplomyny ykrar edilendigi barada maglumat')),
                ('date_of_confirmation', models.DateField(blank=True, verbose_name='Daşary ýurt diplomyny ykrar edilen senesi')),
                ('education_degree', models.CharField(max_length=50, verbose_name='Bilimi')),
                ('major', models.CharField(max_length=100, verbose_name='Hünäri')),
                ('scientific_degree', models.CharField(max_length=100, verbose_name='Hünäri')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Bilimi barada maglumat',
                'verbose_name_plural': 'Bilimi barada maglumatlar',
            },
        ),
    ]
