# Generated by Django 4.2.3 on 2023-07-12 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participateinelections',
            options={'verbose_name': 'Saýlawly edaralara gatnaşmagy barada maglumat', 'verbose_name_plural': 'Saýlawly edaralara gatnaşmagy barada maglumatlar'},
        ),
        migrations.AlterField(
            model_name='personeducation',
            name='confirmation_of_education',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Daşary ýurt diplomyny ykrar edilendigi barada maglumat'),
        ),
        migrations.AlterField(
            model_name='personeducation',
            name='date_of_confirmation',
            field=models.DateField(blank=True, null=True, verbose_name='Daşary ýurt diplomyny ykrar edilen senesi'),
        ),
        migrations.AlterField(
            model_name='personeducation',
            name='date_of_finishing_academy',
            field=models.DateField(blank=True, null=True, verbose_name='Ýokary okuw jaýyndan soňky okuwy tamamlan ýyly'),
        ),
        migrations.AlterField(
            model_name='personeducation',
            name='full_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Gaýbana'),
        ),
        migrations.AlterField(
            model_name='personeducation',
            name='name_of_academy',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ýokary okuw jaýyndan soňky okan ýeri'),
        ),
        migrations.AlterField(
            model_name='personeducation',
            name='remote',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Gündizki'),
        ),
        migrations.AlterField(
            model_name='personeducation',
            name='scientific_degree',
            field=models.CharField(max_length=100, verbose_name='Alymlyk derejesi'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='additional_vacation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_vacation', to='hr_department.additionalvacation', verbose_name='Goşmaça rugsady barada maglumat'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='appreciation_letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciation_letter', to='hr_department.appreciationletter', verbose_name='Hormat hatlary barada maglumat'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='business_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_trip', to='hr_department.businesstrip', verbose_name='Iş sapary barada maglumat'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='car_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_info', to='hr_department.carinfo', verbose_name='Awtoulagy barada maglumat'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='criminal_liability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_liability', to='hr_department.criminalliability', verbose_name='Ýakyn garyndalaşlary jenaýat jogapkärçiligi barada maglumat'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='degree_of_work',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Buýrugyň belgisi'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='foreign_languages',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Haýsy daşary ýurt dillerini bilýär'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='health_vacation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_vacation', to='hr_department.healthvacation', verbose_name='Zähmete ukypsyzlgy boýunça rugsady barada maglumat'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='person_photo'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='order_of_work',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Perkanyň belgisi'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='participate_in_elections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participate_in_elections', to='hr_department.participateinelections', verbose_name='Saýlawly edaralara gatnaşmagy'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='passport_address',
            field=models.CharField(max_length=250, verbose_name='Pasport kim tarapyndan berildi'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='person_education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_education', to='hr_department.personeducation', verbose_name='Bilimi barada maglumat'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefon belgisi'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='phone_number_1',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefon belgisi 2'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='punishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishment', to='hr_department.punishment', verbose_name='Düzgün nyzam jogapkärçiligine çekilmegi barada maglumat'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='relatives_living_abroad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives_living_abroad', to='hr_department.relativeslivingabroad', verbose_name='Ýakyn garyndalaşlary daşary ýurtda ýaşaýanlar barada maglumat'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='rewards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='hr_department.rewards', verbose_name='Döşe dakylýan nyşany barada maglumat'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='state_awards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_awards', to='hr_department.stateawards', verbose_name='Döwlet sylaglary barada maglumat'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='unpaid_leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_leave', to='hr_department.unpaidleave', verbose_name='Tölegsiz zähmet rugsady barada maglumat'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='vacation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation', to='hr_department.vacation', verbose_name='Esasy zähmet rugsady barada maglumat'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='was_he_abroad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='was_he_abroad', to='hr_department.washeabroad', verbose_name='Daşary ýurtda bolanmy'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='work_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='hr_department.workexperience', verbose_name='Iş stažy barada maglumat'),
        ),
    ]
