# Generated by Django 4.2.3 on 2023-07-14 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinformation',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='person_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
