# Generated by Django 4.1.7 on 2023-07-21 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hr_department', '0002_alter_personinformation_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinformation',
            name='user_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
