# Generated by Django 4.1.7 on 2023-07-21 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hr_department', '0003_personinformation_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinformation',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Gözegçilik edýan edara'),
        ),
    ]
