# Generated by Django 4.2.3 on 2023-07-12 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0003_alter_personinformation_additional_vacation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinformation',
            name='relatives_living_abroad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatives_living_abroad', to='hr_department.relativeslivingabroad', verbose_name='Ýakyn garyndalaşlary daşary ýurtda ýaşaýanlar barada maglumat'),
        ),
    ]
