# Generated by Django 4.2.3 on 2023-07-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0003_alter_personeducation_academy_diploma_id_washeabroad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washeabroad',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_WasHeAbroad', to='hr_department.personinformation', verbose_name='Işgär'),
        ),
    ]
