# Generated by Django 4.1.7 on 2023-07-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0004_alter_personinformation_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinformation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='personinformation',
            name='members',
        ),
    ]
