# Generated by Django 4.2.3 on 2023-07-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0004_alter_washeabroad_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_experience', models.SmallIntegerField(verbose_name='Umumy iş döwri')),
                ('experience_in_court', models.SmallIntegerField(verbose_name='Kazyýetde iş döwri')),
                ('experience_in_army', models.SmallIntegerField(verbose_name='Harby gulluk döwri')),
                ('experience_in_education', models.SmallIntegerField(verbose_name='Ýokary okuw döwri')),
                ('experience_in_last_position', models.SmallIntegerField(verbose_name='Soňky wezipedäki iş döwri')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_WorkExperience', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Iş stažy barada maglumat',
                'verbose_name_plural': 'Iş stažy barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='StateAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_award', models.CharField(max_length=250, verbose_name='Döwlet sylagynyň ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Permanyň belgisi')),
                ('order_date', models.DateField(verbose_name='Permanyň senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_StateAwards', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Döwlet sylaglary barada maglumat',
                'verbose_name_plural': 'Döwlet sylaglary barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Buýrugyň belgisi')),
                ('order_date', models.DateField(verbose_name='Buýrugyň senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_Punishment', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Düzgün nyzam jogapkärçiligine çekilmegi barada maglumat',
                'verbose_name_plural': 'Düzgün nyzam jogapkärçiligine çekilmegi barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='AppreciationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Buýrugyň belgisi')),
                ('order_date', models.DateField(verbose_name='Buýrugyň senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_AppreciationLetter', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Hormat hatlary barada maglumat',
                'verbose_name_plural': 'Hormat hatlary barada maglumatlar',
            },
        ),
    ]
