# Generated by Django 4.2.3 on 2023-07-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0005_workexperience_stateawards_punishment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Buýrugyň belgisi')),
                ('order_date', models.DateField(verbose_name='Buýrugyň senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_Vacation', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Esasy zähmet rugsady barada maglumat',
                'verbose_name_plural': 'Esasy zähmet rugsady barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Buýrugyň belgisi')),
                ('order_date', models.DateField(verbose_name='Buýrugyň senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_Rewards', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Döşe dakylýan nyşany barada maglumat',
                'verbose_name_plural': 'Döşe dakylýan nyşany barada maglumatlar',
            },
        ),
    ]
