# Generated by Django 4.2.3 on 2023-07-07 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0006_vacation_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Buýrugyň belgisi')),
                ('order_date', models.DateField(verbose_name='Buýrugyň senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_HealthVacation', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Zähmete ukypsyzlgy boýunça rugsady barada maglumat',
                'verbose_name_plural': 'Zähmete ukypsyzlgy boýunça rugsady barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='AdditionalVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ady')),
                ('order_id', models.CharField(max_length=20, verbose_name='Buýrugyň belgisi')),
                ('order_date', models.DateField(verbose_name='Buýrugyň senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_AdditionalVacation', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Goşmaça rugsady barada maglumat',
                'verbose_name_plural': 'Goşmaça rugsady barada maglumatlar',
            },
        ),
    ]
