# Generated by Django 4.2.3 on 2023-07-07 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0008_unpaidleave_businesstrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalLiability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ady')),
                ('date', models.DateField(verbose_name='Senesi')),
                ('court_info', models.CharField(max_length=200, verbose_name='Ady')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_CriminalLiability', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Ýakyn garyndalaşlary jenaýat jogapkärçiligi barada maglumat',
                'verbose_name_plural': 'Ýakyn garyndalaşlary jenaýat jogapkärçiligi barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Awtoulagyň ady')),
                ('date_manufacture', models.DateField(verbose_name='Öndürilen senesi')),
                ('is_own', models.CharField(max_length=100, verbose_name='Awtoulag kimiň adyna resmilleşdirilen')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_CarInfo', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Awtoulagy barada maglumat',
                'verbose_name_plural': 'Awtoulagy barada maglumatlar',
            },
        ),
    ]
