# Generated by Django 4.2.3 on 2023-07-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0009_criminalliability_carinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelativesLivingAbroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ady, Familiýasy')),
                ('country_name', models.CharField(max_length=100, verbose_name='Ýurduň ady')),
                ('start_date', models.DateField(verbose_name='Giden senesi')),
                ('end_date', models.DateField(verbose_name='Gelen senesi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_RelativesLivingAbroad', to='hr_department.personinformation', verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Ýakyn garyndalaşlary daşary ýurtda ýaşaýanlar barada maglumat',
                'verbose_name_plural': 'Ýakyn garyndalaşlary daşary ýurtda ýaşaýanlar barada maglumatlar',
            },
        ),
    ]
