# Generated by Django 4.2.3 on 2023-07-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0010_relativeslivingabroad'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinformation',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
